version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: plasmox
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: plasmox
      DATABASE_PASSWORD: plasmox123
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: plasmox
      POSTGRES_PASSWORD: plasmox123
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'
#
